### ISSUE TITLE
An error occurred with a learning card

### ISSUE THREAD

**Issue by Raffaele-Melorio** [cjdduarte/Defer_Cards#4]
Debug info:
Anki 2.1.66 (70506aeb) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: macOS-14.0-arm64-arm-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-10-23 06:08:55
Add-ons possibly involved: ⁨Defer Cards⁩

```
Caught exception:
Traceback (most recent call last):
  File "/Users/main/Library/Application Support/Anki2/addons21/149564514/defer_cards.py", line 63, in defer
    self.swap(did, card)
  File "/Users/main/Library/Application Support/Anki2/addons21/149564514/defer_cards.py", line 84, in swap
    if card.queue==1 and mw.col.sched.name != "std2":
  File "anki._legacy", line 80, in __getattr__
AttributeError: 'Scheduler' object has no attribute 'name'
```

**Comment by cjdduarte** [comment]
hank you. I will check here
