### ISSUE TITLE
startup fail,Anki 24.06.3

### ISSUE THREAD

**Issue by tomtomtomtony** [cjdduarte/Defer_Cards#7]
Hi,cjdduarte
there is some wrong.
Debug info:
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.22621

Traceback (most recent call last):
  File "aqt.webview", line 50, in cmd
  File "aqt.webview", line 160, in _onCmd
  File "aqt.webview", line 695, in _onBridgeCmd
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 86, in repl
  File "C:\Users\tom\AppData\Roaming\Anki2\addons21\149564514\defer_cards.py", line 178, in custom_pycmd_handler
    on_custom_button_click()
  File "C:\Users\tom\AppData\Roaming\Anki2\addons21\149564514\defer_cards.py", line 173, in on_custom_button_click
    sd.defer()  # Chama a função defer() do DeferCards
  File "C:\Users\tom\AppData\Roaming\Anki2\addons21\149564514\defer_cards.py", line 63, in defer
    self.swap(did, card)
  File "C:\Users\tom\AppData\Roaming\Anki2\addons21\149564514\defer_cards.py", line 84, in swap
    if card.queue == 1 and mw.col.sched.name != "std2":
  File "anki._legacy", line 80, in __getattr__
AttributeError: 'Scheduler' object has no attribute 'name'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Add Table ['1237621971', 2023-06-18T19:37, 'None', '']
AnkiConnect ['2055492159', 2024-07-26T12:55, 'None', '']
Defer Cards Not to answer them immediately ['149564514', 2024-09-25T23:02, 'None', '']
Image Occlusion Enhanced ['1374772155', 2022-04-09T15:15, 'None', '']
Mini Format Pack ['295889520', 2023-11-03T02:00, 'None', '']
link Cards Notes and Preview them in extra window ['1423933177', 2023-10-28T06:26, 'None', '']

===IDs of active AnkiWeb add-ons===
1237621971 1374772155 1423933177 149564514 2055492159 295889520

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Syntax Highlighting NG ['566351439', 2024-07-19T17:46, 'None', '']

**Comment by cjdduarte** [comment]
I will evaluate the bug and get back to you as soon as possible

**Comment by cjdduarte** [comment]
Fixed compatibility issues with Scheduler attribute in Anki 24.06+
